### ISSUE TITLE
Making our working branch up-to-date

### ISSUE THREAD

**Issue by gochist** [kubernetes/kubernetes-docs-ko#12]
It is first localization for us after Hugo migration, SIG Docs encouraged us to find a good solution about branching strategy and share it with other l10n team. Using subtree was one of the candidates but I can’t figure out a good workflow with it.

Currently our working branch, k/k-docs-ko `dev-1.12` was checked out from k/website `release-1.12` branch. Our working branch is already outdated so far from current k/website `release-1.12` branch. So we need to update `dev-1.12` so that it can catch up `release-1.12` of k/website. 

These are the tasks to do when we update `dev-1.12`:

1. Make a list of changed files in `content/en` from `dev-1.12` to w/website `release-1.12`. If we have any corresponding file with the list in `content/ko`, they are the outdated files. So we need to open an issue to update them.
2. We need to separate our local commits from main repo commits so that we can make a single squashed commit easily when we open our first PR to main repo. 
3. From our second PR, the local commits used for the first PR should be backed up somewhere else, and we need to update our working branch again.

It is not hard for doing no.1. I write [my own script](https://gist.github.com/gochist/8654460717b4bbb4ac490dda79a547fa) and it works.

For no.2, rebasing `dev-1.12` onto `k/website release-1.12` with a command line like `git rebase –onto website/release-1.12 HEAD~#N` will work where #N is the number of our local commits. 

But I not sure that we can rebase the public working branch without side-effect. Any good idea?

**Comment by claudiajkang** [comment]
`2018-08-28 회의` 안건에 추가했습니다.

**Comment by gochist** [comment]
@zparnold  @jimangel I translated and updated this issue in English. Thank you for your help in advance.

**Comment by gochist** [comment]
According to the [Branching Tactics For k/k-docs-ko](https://docs.google.com/presentation/d/14x_kLkk6cAvF04uDwIYTGWuE_bFxPY83MvrCb9nHfxE/edit#slide=id.p), I made our working branch up-to-date by #40, #41 and #42 . This tactics will be applied until we find a better solution.
