### ISSUE TITLE
한글 문서화에 어떻게 기여할 수 있을까요?

### ISSUE THREAD

**Issue by yoonian** [kubernetes/kubernetes-docs-ko#2]
한글화에 기여하는 방법이 정리되어 있으면 좋겠습니다.

일단 접근하기 쉬운 Wiki 나 README.MD 에서 부터요.

PR 하나 보낼 때에도 의외로 확인 할 것이 많아서. 빠르게 시작할 수 있는 가이드가 필요할 듯 싶습니다.

이야기 드렸던 것이지만, 요 이슈를 시작으로 계속 진행하면 좋겠습니다.

**Comment by yoonian** [comment]
기여 방법에 대해 [CONTRIBUTION.MD](https://github.com/kubernetes/kubernetes-docs-ko/blob/master/CONTRIBUTING.md)는 존재하지만, 우선 여기에 대략적으로 기록하여 봅니다.

쿠버네티스 프로젝트는 CNCF 소유이므로, 먼저 [Contributor License Agreement, 이하 CLA](https://github.com/kubernetes/community/blob/master/CLA.md) 에 서명하셔야 합니다.

서명 전에 [Code of Conduct, 이하 행동강령](https://github.com/cncf/foundation/blob/master/code-of-conduct.md)을 꼭 숙지하시고 진행하시기 바랍니다.

1. Github 에 가입
2. Linux Foundation 을 Github 에 가입한 e-mail 로 가입
  - 가입할 때에는 개인과 기업으로 나뉘는데, 여기서는 개인인 경우로 한정하여 설명합니다.
3. Linux Foundation 에 Github 으로 연동
  - 등록한 e-mail 로 CLA 에 전자서명을 할 수 있는 링크가 전달됩니다.
4. CLA 에 서명
  - 등록한 e-mail 에 보내진 링크를 따라서, `REVIEW & SIGN` 클릭 후 내용 확인하고 서명하시면 됩니다.
  - 종이 문서를 선호하신다면, 직접 [CLA 문서](https://github.com/cncf/cla/blob/master/individual-cla.pdf)를 인쇄해서 자필 서명하시고 스캔해서 이메일로 보내는 방법도 있습니다.
5. CLA 서명 완료
  - 서명 완료가 확인되면, `You just signed CNCF Individual Contributor License Agreement`  제목으로 메일이 발송됩니다.

서명 완료 이후에 Pull Request 를 보낼 자격을 획득합니다.

쿠버네티스 문서 한글화를 위해 Kubernetes Docs Special-Interest-Group(SIG) 내에 서브 워킹 그룹으로 한글화 팀이 있습니다.  kubernetes 슬랙에 #kubernetes-docs-ko 채널이 개설되어 있으며, kubernetes 슬랙 가입은 [slack.k8s.io](http://slack.k8s.io) 을 통해서 하실 수 있습니다.

**Comment by HyunSooKim7854** [comment]
위의 설명이 다소 간단하여, 처음 사용하는 사람들에게 어려울 수 있을 것 같습니다.
캡처 그림 등으로, 자세하게 설명하면 좋은 것 같은데요.
제가 수정해도 되나요?

**Comment by gochist** [comment]
@HyunsooKim1112 #3 으로 진행 중 입니다. 이미지 캡처가 포함된 [CLA](https://github.com/kubernetes/community/blob/master/CLA.md)문서를 링크하는 걸로 갈음하면 어떨까요?

**Comment by yoonian** [comment]
@HyunsooKim1112 @gochist 언급하신 [CLA](https://github.com/kubernetes/community/blob/master/CLA.md)의 내용을 참고해서 수정하면 될듯 합니다.

**Comment by gochist** [comment]
@yoonian @HyunsooKim1112 쿠버네티스 프로젝트 템플릿([k/k-template-project](https://github.com/kubernetes/kubernetes-template-project)) 또는 [k/website](https://github.com/kubernetes/website/)의 컨텐츠가 아닌 다른 저장소(본 건의 경우, [k/community](https://github.com/kubernetes/community))의 컨텐츠를 우리 저장소에 옮기거나, 우리만의 독자적인 프로세스도 아닌데 새로운 컨텐츠를 생산하게 되는 건이 되어서 조심스럽습니다. 

@HyunsooKim1112 #3 을 함께 진행할 수 있도록 Invitation Link를 보내드렸습니다.

**Comment by HyunSooKim7854** [comment]
@gochist @yoonian 님께서 말씀하신 해당 링크의 내용이면 충분할 것 같습니다.
그냥 참고할 수 있도록 링크만 걸어도 괜찮을 듯 하구요, 아니면 해당 내용을 한글화해서 추가하는 것도 가능할 것 같습니다.

**Comment by gochist** [comment]
2018-08-14 회의에서 CLA 가이드 한글화(#4) 이슈를 따로 분리하기로 했습니다.
