### ISSUE TITLE
문체 통일 - 경어체/평어체

### ISSUE THREAD

**Issue by gochist** [kubernetes/kubernetes-docs-ko#20]
의사 결정을 위한 의견 주세요.

**Comment by zer0big** [comment]
Azure 의 한글화 사례를 참조해보니, 경어체로 되어 있네요. 경어체로 가는데 한표 던집니다.

**Comment by BoomLEE** [comment]
**경어체**
제 의견은 평어체 보다는 **경어체**가 정보를 전달하는 문서에 적합하다고 생각합니다.
・자신의 주간적 감정이나 정서를 전달하는 글 (기행문, 편지글, 수필)이라면 평어체가 적합하다고(효과적) 생각합니다.
・경어체가 상대적으로 개인의 개성이 적게 나타난다고 생각하기 떄문에, 여러 사람이 번역하는 문서/글인 쿠버네티스 웹페이지에 적합하다고 생각합니다.

**Comment by gochist** [comment]
저는 평어체를 주장합니다.

대부분의 과학/기술 출판물이 평어체로 기술되고 있고, 개인적으로 ['나는 경어체 문장이 불편하다'](http://www.ohmynews.com/NWS_Web/View/at_pg.aspx?CNTN_CD=A0002399993)는 기사 내용에 공감합니다. 저희가 다룰 문서의 대부분의 내용은 독자에게 친근하게 다가갈 성격의 문서라기 보다 객관적인 사실을 기술할 문서라고 생각하기 때문입니다.

@BoomLEE 논리는 같은데 결과가 반대네요. 평어체가 아무래도 감정이 배제된 객관적인 문체 아닐까요?
@zer0big Azure의 문서처럼 고객을 대상으로 하는 매뉴얼이 경어체를 선택하는 것은 이해가 갑니다.

**Comment by zer0big** [comment]
평어체로 다시 변경~^

@gochist 넵, Azure 의 기술 가이드 문서 기준으로 말씀드린거구요. 평상시 저도 주로 평어체로 작성하고 있긴 합니다. 제시하신 근거에 공감이 됩니다. 기술 가이드인 만큼 말씀하신 것 처럼 다소 객관적인 뉘앙스가 적합할 듯 하네요.

**Comment by gochist** [comment]
9/4 회의에서 결정할 예정입니다. 의견 모아주세요!

**Comment by gochist** [comment]
9/4 회의에서는 평어체를 기준으로 하기로 결정했습니다. 단, 예외 적용에 대한 논의는 계속 진행 중입니다.

**Comment by gochist** [comment]
Welcome Page에만 경어체 예외 적용

/close
