### ISSUE TITLE
Need admin access

### ISSUE THREAD

**Issue by chenopis** [kubernetes/kubernetes-docs-ko#23]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
@chenopis and @lucperkins need admin access to this repo so we can setup the Netlify hosting for preview builds.

**Proposed Solution:**
Add @chenopis and @lucperkins to kubernetes-docs-ko-admins group.

**Page to Update:**
https://github.com/orgs/kubernetes/teams/kubernetes-docs-ko-admins/members

**Comment by zacharysarah** [comment]
@lucperkins Have you completed K8s org membership? I’m unable to add you as an admin.
