### ISSUE TITLE
CLA 가이드 한글화

### ISSUE THREAD

**Issue by gochist** [kubernetes/kubernetes-docs-ko#4]
CLA 가이드 한글화 페이지 추가

**Comment by gochist** [comment]
@HyunsooKim1112 시스템 상 할당이 안되네요. 위키 편집 가능 여부 확인 부탁드립니다.

**Comment by HyunSooKim7854** [comment]
확인해 보고 알려 드리겠습니다.

--
Best Regards,
Hyunsoo Kim
+82-10-5367-7854
Sent from my iPhone

2018. 8. 14. 23:31, June Yi <notifications@github.com> 작성:

**Comment by ianychoi** [comment]
@HyunsooKim1112 안녕하세요. https://github.com/k8s-kr `org` 에 초대하였습니다. 위 코멘트와 같이 시스`kubernetes/kubernetes-docs-ko` 저장소에 직접 편집이 안되기에 https://github.com/k8s-kr/kubernetes-docs-ko/wiki 위키 페이지에서 먼저 편집을 하고 그 결과를 반영하는 프로세스로 가고자 합니다. `invite` 확인 부탁드립니다.
