### ISSUE TITLE
ONWERS under contents/ko directory

### ISSUE THREAD

**Issue by gochist** [kubernetes/kubernetes-docs-ko#46]
According to the SIG Docs APAC meeting 2018-09-26(KST)
- [ ] Revert OWNERS file on the root directory to contains upstream maintainers
- [ ] Move current OWNERS file which contains k/k-docs-ko maintainers to `contents/ko` directory

**Comment by claudiajkang** [comment]
ko/OWNERS file related kubernetes/website issue : [#10485](https://github.com/kubernetes/website/pull/10485)
