### ISSUE TITLE
[Tutorials > Hello minikube] 페이지 번역

### ISSUE THREAD

**Issue by claudiajkang** [kubernetes/kubernetes-docs-ko#5]
> 기준 브랜치 : [dev-1.12](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12)
> 번역 범위 : 전체

**1. 번역할 페이지 리스트**
  - [x] [1. hello-minikube](https://kubernetes.io/docs/tutorials/hello-minikube.md) | [파일](https://github.com/kubernetes/website/tree/release-1.12/content/en/docs/tutorials/hello-minikube.md) 

**2. 번역 파일 업데이트 경로**
https://github.com/kubernetes/kubernetes-docs-ko/content/ko/docs/tutorials/hello-minikube.md

> 참고 : [한글화 용어집](https://goo.gl/BDNeJ1)

**Comment by lawlait** [comment]
Assign 받고 싶습니다. @gochist 님께 PR 보내달라는 부분 전달 받았고, dev-1.12 프랜치 사용예정입니다.

**Comment by gochist** [comment]
이슈 할당은 거버넌스 상 쿠버네티스 멤버에게만 가능합니다. 커멘트 주셨으니 다른 분들이 중복작업 않으실거라 믿어봅니다.
