### ISSUE TITLE
[Tutorials > Kubernetes Basics] 페이지 번역

### ISSUE THREAD

**Issue by claudiajkang** [kubernetes/kubernetes-docs-ko#6]
> 기준 브랜치 : [dev-1.12](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12)
> 번역 범위 : 전체 

**1. 번역할 페이지 & 파일 리스트**
  - [X] [1. Overview](https://kubernetes.io/docs/tutorials/kubernetes-basics/index.html) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/tutorials/kubernetes-basics/index.html)
  - [X] [2. Create a Cluster](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html) 
  - [X] [3. Deploy an App](https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html)  | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html) 
  - [x] [4. Explore Your App](https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro.html) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/tutorials/kubernetes-basics/explore/explore-intro.html) 
  - [x] [5. Expose Your App Publicly](https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro.html) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html) 
  - [X] [6. Scale Your App](https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro.html) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html) 
  - [X] [7. Update Your App](https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro.html) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/tutorials/kubernetes-basics/update/update-intro.html) 

**2. 번역 파일 업데이트 경로**
https://github.com/kubernetes/kubernetes-docs-ko/content/ko/docs/tutorials/kubernetes-basics/파일명

> 참고 : [한글화 용어집](https://goo.gl/BDNeJ1)

**Comment by gochist** [comment]
@ClaudiaJKang 페이지 링크가 k8s-kr 저장소로 되어있는데 docs.kubernetes.io 쪽으로 바꾸는게 어떨까요?

**Comment by claudiajkang** [comment]
@gochist 수정했습니다.

**Comment by gochist** [comment]
제가 `create-cluster` 부분을 진행해 보겠습니다.

**Comment by gochist** [comment]
제가 `deploy-app` 부분도 진행하겠습니다.

**Comment by zer0big** [comment]
제가 Expose Your App Publicly 맡아서 진행해보고 싶습니다.

**Comment by gochist** [comment]
`scale` 도 진행했습니다.

**Comment by zer0big** [comment]
Explore Your App 진행하도록 하겠습니다.

**Comment by zer0big** [comment]
Update Your App 진행하도록 하겠습니다.

**Comment by gochist** [comment]
overview 진행했습니다.
