### ISSUE TITLE
[Documentation Home] 페이지 heading, subheading URL 번역

### ISSUE THREAD

**Issue by claudiajkang** [kubernetes/kubernetes-docs-ko#7]
> 기준 브랜치 : [dev-1.12](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12)
> 번역 범위 : heading, subheading URL

**1. 번역할 페이지 리스트**
  - [x] [home/_index.md](https://kubernetes.io/docs/home/index.html) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/home/_index.md)
  - [x] [glossary/index.md](https://kubernetes.io/docs/reference/glossary/index.html) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/reference/glossary/index.md)

**2. 번역 파일 업데이트 경로**
https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/ko/docs/home/_index.md
https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/ko/docs/reference/glossary/index.md

**Comment by gochist** [comment]
"[Home]" 이라는 말머리는 https://kubernetes.io/docs/home/ 페이지가 연상됩니다.

**Comment by gochist** [comment]
워킹 브랜치를 업스트림에 머지할 것을 생각하면 충돌이 발생하지 않도록  `content/ko` 디렉토리 내 컨텐츠만 수정해야 할 것 같습니다.( `config.toml` 파일은 예외)  아래 두 파일만 있으면 에러 없이 빌드됩니다. 

* `content/ko/docs/home/_index.md`
* `content/ko/docs/reference/glossary/_index.md`
