### ISSUE TITLE
[Setup] 페이지 heading, subheading URL 번역

### ISSUE THREAD

**Issue by claudiajkang** [kubernetes/kubernetes-docs-ko#8]
> 기준 브랜치 : [dev-1.12](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12)
> 번역 범위 : heading, subheading URL

**1. 번역할 페이지 리스트**
  - [x] [1. _index](https://kubernetes.io/docs/setup) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/_index.md)
  - [x] [2. independent/_index](https://kubernetes.io/docs/setup/independent) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/independent/_index.md)
  - [x] [3. turnkey/_index](https://kubernetes.io/docs/setup/turnkey) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/turnkey/_index.md)
  - [x] [4. on-premises-vm/_index](https://kubernetes.io/docs/setup/on-premises-vm) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/on-premises-vm/_index.md)
  - [x] [5. custom-cloud/_index](https://kubernetes.io/docs/setup/custom-cloud) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/custom-cloud/_index.md)
  - [x] [6. Building Large Clusters](https://kubernetes.io/docs/setup/cluster-large) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/cluster-large.md)
  - [x] [7. Building from Source](https://kubernetes.io/docs/setup/building-from-source) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/building-from-source.md)
  - [ ] ~~[8. Configuring Kubernetes with Salt](https://kubernetes.io/docs/setup/salt) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/salt.md)~~
  - [x] [9. Creating a Custom Cluster from Scratch](https://kubernetes.io/docs/setup/scratch) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/scratch.md)
  - [x] [10. Picking the Right Solution](https://kubernetes.io/docs/setup/pick-right-solution) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/pick-right-solution.md)
  - [x] [11. Running Kubernetes Locally via Minikube](https://kubernetes.io/docs/setup/minikube) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/minikube.md)
  - [x] [12. Running in Multiple Zones](https://kubernetes.io/docs/setup/multiple-zones) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/multiple-zones.md)
  - [x] [13. Validate Node Setup](https://kubernetes.io/docs/setup/node-conformance) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/node-conformance.md)

**2. 번역 파일 업데이트 경로**
https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/ko/docs/setup/파일명

> 참고 : [한글화 용어집](https://goo.gl/BDNeJ1)

**Comment by claudiajkang** [comment]
`[Setup] 페이지 heading, subheading URL 번역 ` 부분 진행해 보겠습니다.

**Comment by gochist** [comment]
@ClaudiaJKang 한 번의 PR로 처리할 필요 없습니다. 나누어서 올려도 될 것 같습니다.
